# Generated by Django 4.2.7 on 2026-04-29 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("building", models.CharField(max_length=255)),
                (
                    "venue_type",
                    models.CharField(
                        choices=[
                            ("lecture_hall", "Lecture Hall"),
                            ("office", "Office"),
                            ("laboratory", "Laboratory"),
                            ("library", "Library"),
                            ("cafeteria", "Cafeteria"),
                            ("bookshop", "Bookshop"),
                            ("auditorium", "Auditorium"),
                            ("wellness_center", "Wellness Center"),
                            ("computer_lab", "Computer Lab"),
                            ("sports_facility", "Sports Facility"),
                            ("parking", "Parking"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=8, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=8, max_digits=11)),
                ("capacity", models.IntegerField(blank=True, null=True)),
                ("amenities", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("floor_number", models.IntegerField(blank=True, null=True)),
                ("is_accessible", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "venues",
                "unique_together": {("name", "building")},
            },
        ),
    ]
